name: weather_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0' 

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0 
  shared_preferences: ^2.1.1  
  cached_network_image: ^3.2.3 
  flutter_spinkit: ^5.2.1 
  provider: ^6.1.2  
  cupertino_icons: ^1.0.6 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
